services:
  - docker

before_script:
  - curl https://cli-assets.heroku.com/install.sh | sh
  - echo "$HEROKU_API_KEY" | docker login --username=$HEROKU_USERNAME --password-stdin registry.heroku.com

script:
  - heroku container:push bot --app=$HEROKU_APP_NAME
  - heroku container:release bot --app=$HEROKU_APP_NAME
